#!/usr/bin/env python3

BUS = 'http://m.bus.go.kr/mBus/bus/'
SUBWAY = 'http://m.bus.go.kr/mBus/subway/'
PATH = 'http://m.bus.go.kr/mBus/path/'

all_bus_routes = BUS + 'getBusRouteList.bms'
bus_route_search = all_bus_routes + '?strSrch={0}'
bus_route_by_id = BUS + 'getRouteInfo.bms?busRouteId={0}'
all_low_bus_routes = BUS + 'getLowBusRoute.bms'
low_bus_route_search = all_low_bus_routes + 'strSrch={0}'
all_night_bus_routes = BUS + 'getNBusRoute.bms'
night_bus_route_search = all_night_bus_routes + 'strSrch={0}'
all_airport_bus_routes = BUS + 'getAirBusRoute.bms'
bus_routes_by_type = BUS + 'getRttpRoute.bms?strSrch={0}&stRttp={1}'
route_path_by_id = BUS + 'getRoutePath.bms?busRouteId={0}'
route_path_detailed_by_id = BUS + 'getStaionByRoute.bms?busRouteId={0}'
route_path_realtime_by_id = BUS + 'getRttpRouteAndPos.bms?busRouteId={0}'
low_route_path_realtime_by_id = BUS + 'getLowRouteAndPos.bms?busRouteId={0}'
bus_arrival_info_by_route = BUS + 'getArrInfoByRouteAll.bms?busRouteId={0}'
bus_arrival_info_by_route_and_station = BUS + 'getArrInfoByRoute.bms?busRouteId={0}&stId={1}&ord=1'
bus_stations_by_position = BUS + 'getStationByPos.bms?tmX={0}&tmY={1}&radius={2}'
routes_by_position = BUS + 'getNearRouteByPos.bms?tmX={0}&tmY={1}&radius={2}'
bus_stations_by_name = BUS + 'getStationByName.bms?stSrch={0}'
low_bus_stations_by_name = BUS + 'getLowStationByName.bms?stSrch={0}'
routes_by_bus_station = BUS + 'getRouteByStation.bms?arsId={0}'
arrival_info_by_bus_station = BUS + 'getStationByUid.bms?arsId{0}'
low_arrival_info_by_bus_station = BUS + 'getLowStationByUid.bms?arsId{0}'
operating_times_by_bus_station_and_route = BUS + 'getBustimeByStation.bms?arsId={0}&busRouteId={1}'
bus_position_by_route = BUS + 'getBusPosByRtid.bms?busRouteId={0}'
low_bus_position_by_route = BUS + 'getLowBusPosByRtid.bms?busRouteId={0}'
bus_position_by_id = BUS + 'getBusPosByVehId.bms?vehId={0}'

closest_station_by_position = PATH + 'getNearStationByPos.bms?tmX={0}&tmY={1}&radius={2}'
location_by_name = PATH + 'getLocationInfo.bms?stSrch={0}'
path_by_bus = PATH + 'getPathInfoByBus.bms?startX={0}&startY={1}&endX={2}&endY={3}'
path_by_subway = PATH + 'getPathInfoBySubway.bms?startX={0}&startY={1}&endX={2}&endY={3}'
path_by_bus_and_subway = PATH + 'getPathInfoByBusNSub.bms?startX={0}&startY={1}&endX={2}&endY={3}'

all_subway_stations = SUBWAY + 'getStatnByNm.bms'
subway_stations_by_name = all_subway_stations + '?statnNm={0}'
subway_stations_by_route = SUBWAY + 'getStatnByRoute.bms?subwayId={0}'
subway_arrival_info_by_route_and_station = SUBWAY + 'getArvlByInfo.bms?subwayId={0}&statnId={1}'
subway_station_by_route_and_id = SUBWAY + 'getStatnById.bms?subwayId={0}&statnId={1}'
subway_timetable_by_route_and_station = SUBWAY + 'getPlanyByStatn.bms?subwayId={0}&statnId={1}&tabType={2}'
first_and_last_subway_by_route_and_station = SUBWAY + 'getLastcarByStatn.bms?subwayId={0}&statnId={1}'
bus_stations_by_subway_station = SUBWAY + 'getBusByStation.bms?statnId={0}'
subway_entrance_info_by_station = SUBWAY + 'getEntrcByInfo.bms?statnId={0}'
subway_station_position_by_id = SUBWAY + 'getStatnByIdPos.bms?statnId={0}'
train_info_by_subway_route_and_station = SUBWAY + 'getStatnTrainInfo.bms?subwayId={0}&statnId={1}'
